### ISSUE TITLE
Generalize Entity Matching Framework 

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/ccai-entity-matching#106]
## Background
The code in this repo was developed specifically with the FERC-EIA matching problem, but ideally should be usable for other matching problems. The core underlying modelling is not dependent on this problem, but the implementation is currently tooled specifically to work with these inputs.

```[tasklist]
### Tasks
- [ ] https://github.com/catalyst-cooperative/ccai-entity-matching/issues/107
- [ ] Test matching with new generalized framework
- [ ] Compare results vs existing PUDL matching
- [ ] Test generalized framework with FERC-FERC inter-year matching
```
