### ISSUE TITLE
Evaluate and compare current performance of models

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/ccai-entity-matching#110]
As we start to integrate the CCAI modelling work back into PUDL, we need to have a concrete understanding of the performance vs our baselines. Here are some comparisons that can be done that may lead to potential understanding and improvement:

```[tasklist]
### Tasks
- [x] Run the splink model with the same train test split as in the PUDL model and compare results on test set to those of PUDL model
- [x] Look at the output matches of the splink model (unsupervised and supervised) and compare to the existing matches from the PUDL model
- [x] Try running splink model with all the columns that are used for feature embedding in the existing PUDL model
- [ ] Try running the existing PUDL model with the blocking column generated by `faiss` clustering, do results improve?
- [ ] Try running the existing PUDL model with simple imputations for null columns from the CCAI repo.
```

**Comment by katie-lamb** [comment]
Writing this here just to make a note:

unsupervised splink and supervised splink models are performing around the same:
- .87 on test set (same on full train set), .83 when math probability threshold = .5

existing PUDL linear model:
- .73 on test set (.87 on full train set)

Seems like the splink model generalizes better.

**Comment by katie-lamb** [comment]
Comparing the precision and recall of the PUDL model vs splink models at different match probability thresholds (.9, .75, .5, .25):
![Screen Shot 2024-01-23 at 9 19 27 PM](https://github.com/catalyst-cooperative/ccai-entity-matching/assets/95320980/368b44c5-67d8-4b41-915e-c1a9bed1a124)

Comparing the supervised splink model vs the unsupervised model:
![Screen Shot 2024-01-23 at 9 19 38 PM](https://github.com/catalyst-cooperative/ccai-entity-matching/assets/95320980/5e2187d0-9381-412a-a540-90935cc2709e)

Comparing the number of duplicate EIA plant parts that appear in the matched data (multiple FERC records are matched to the same EIA plant part) in the splink supervised vs PUDL:
![Screen Shot 2024-01-23 at 9 19 31 PM](https://github.com/catalyst-cooperative/ccai-entity-matching/assets/95320980/57cbc3c1-f25f-48b9-b931-500ba4882037)

While it's a matter of preferences in what we optimize for that ultimately decides which model parameters to use, it seems clear that we should integrate some version of the splink model (probably the supervised and leave a notebook with the unsupervised version)
