### ISSUE TITLE
Set up record-linkage experiment infrastructure

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/ccai-entity-matching#37]
We've got a bunch of (potential) experiments that we want to compare, so setting up a framework for running them all in repeatable way will be helpful

```[tasklist]
- [x] Switch to pulling nightly build DB from S3 rather than datasette (#41 )
- [x] #38 (#41)
- [x] #39 (#41)
- [ ] #32
- [ ] https://github.com/catalyst-cooperative/ccai-entity-matching/issues/48
- [ ] unpin `pudl` dependency from commit and use `main` once nightly builds are running on `main`
- [ ] integrate utility name merge onto PPL into the PUDL `plant_parts_eia` analysis
```
